<?php

namespace Ecorso\Transaction;

use Doctrine\Common\Collections\ArrayCollection;
use Ecorso\Transaction\Transaction;
use Ecorso\Transaction\TransactionId;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * Repository methods below.
 */
interface TransactionRepositoryInterface
{
    public function find($id) : Transaction;

    public function findAll() : TransactionCollection;

    public function add(Transaction $transaction) : void;

    public function remove(Transaction $transaction) : void;
}
