<?php

namespace Ecorso\User;

use Doctrine\Common\Collections\ArrayCollection;
use Ecorso\User\User;
use Ecorso\User\UserId;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * Repository methods below.
 */
interface UserRepositoryInterface
{
    public function find($id) : User;

    public function findAll() : UserCollection;

    public function add(User $user) : void;

    public function remove(User $user) : void;
}
